app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, MultipleFileField
from wtforms.validators import DataRequired, Length
from flask_wtf.file import FileAllowed


class NewsForm(FlaskForm):
    title = StringField('Название',
                        validators=[DataRequired(message="Поле пусто!"), Length(1, 128, message='От 1 до 128 символов длиной')])
    news = TextAreaField('Новость',
                        validators=[DataRequired(message='Содержание не должно быть пустым'), Length(1, 1024, message='Длина новости ограничена 1024 символами.')])
    image = MultipleFileField('', id="formFileMultiple", validators=[FileAllowed('avatars', message='Только изображения')])
    submit = SubmitField('Опубликовать')

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__, template_folder='templates')

from . import views
from ..models import Permission


@main.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)

app/main/views.py
from . import main
from ..form import SearchForm
from flask import render_template, request, current_app
from .. import db
from ..models import User, Manga, News, logs, Comment, Tag, manga_tag, Chapter

@main.route('/')
def index():
    search_form = SearchForm()
    
    new_manga = Manga.query.order_by(Manga.timestamp.desc())

    popular_manga = db.session.query(Manga, db.func.count(logs.c.user_id).label('popular')) \
                                .join(logs) \
                                .group_by(Manga) \
                                .order_by(db.text('popular DESC')) \
                                .limit(5).from_self(Manga)
    popular_users = db.session.query(User, db.func.count(Comment.user_id).label('popular')) \
                                .join(Comment) \
                                .group_by(User) \
                                .order_by(db.text('popular DESC')) \
                                .limit(5).from_self(User)
    popular_tags = db.session.query(Tag, db.func.count(manga_tag.c.tag_id).label('popular')) \
                                .join(manga_tag) \
                                .group_by(Tag) \
                                .order_by(db.text('popular DESC')) \
                                .limit(48).from_self(Tag)
    new_chapters = db.session.query(Manga, Chapter, db.func.max(Chapter.timestamp).label('timestamp')) \
                                .join(Chapter) \
                                .group_by(Manga.id, Chapter.id) \
                                .order_by(db.text('timestamp DESC')).limit(8).from_self(Manga, Chapter)

    last_news = News.query.order_by(News.timestamp.desc()).limit(6)
    
    page = request.args.get('page', 1, type=int)
    pagination_new_manga = new_manga.paginate(
    page, per_page=current_app.config['MANGA_LIST_PER_PAGE'],
    error_out=False)
    return render_template('index.html', search_form=search_form, popular_manga=popular_manga, popular_users=popular_users, \
                            last_news=last_news, popular_tags=popular_tags, new_chapters=new_chapters, pagination_new_manga=pagination_new_manga, title="Главная")


@main.route('/manga-list', methods=['GET'])
def manga_list():
    search_word = request.args.get('search', None)
    search_form = SearchForm()
    manga = Manga.query
    if search_word:
        manga = manga.filter(Manga.title.ilike('%' + search_word + '%'))
        search_form.search.data = search_word
    else:
        manga = manga.order_by(Manga.timestamp.desc())
    page = request.args.get('page', 1, type=int)
    pagination = manga.paginate(
    page, per_page=current_app.config['MANGA_LIST_PER_PAGE'],
    error_out=False)
    return render_template('manga_list.html', search_form=search_form, pagination=pagination, title="Манга")

@main.route('/users-list', methods=['GET'])
def users_list():
    search_word = request.args.get('search', None)
    search_form = SearchForm()
    users = User.query
    if search_word:
        users = users.filter(User.username.ilike('%' + search_word + '%'))
        search_form.search.data = search_word
    page = request.args.get('page', 1, type=int)
    pagination = users.paginate(
    page, per_page=current_app.config['USER_LIST_PER_PAGE'],
    error_out=False)
    return render_template('users_list.html', search_form=search_form, pagination=pagination, title="Пользователи")

@main.route('/news-list')
def news_list():
    news = News.query.order_by(News.timestamp.desc())
    page = request.args.get('page', 1, type=int)
    pagination = news.paginate(
    page, per_page=current_app.config['NEWS_LIST_PER_PAGE'],
    error_out=False)
    return render_template('news_list.html', pagination=pagination, title="Новости")

app/main/templates/index.html
{% extends "base.html" %}
{% import "_pagination.html" as pagination %}
{% import "_manga.html" as manga %}
{% import "_news.html" as news %}
{% import "_tags.html" as tags %} 
{% import "_top_users.html" as top_users %}
{% import "_chapters.html" as chapters%}

{% block page_content %}
<form class="d-flex" method="get" action="{{ url_for('main.manga_list') }}">
    {{ search_form.search(placeholder="Поиск манги",class_="form-control me-2") }}
    {{ search_form.submit(class_="btn btn-primary") }}
</form>
<div class="row mt-4" >
  <div class="col-9">
    <h6 class="mb-3">Популярная манга</h6>
    <div class="anime-grid">
      {{manga.widget(popular_manga, current_user)}}
    </div>
    <h6 class="mb-3 mt-4">Последние новости</h6>
    <div class="news-grid">
      {{news.widget(last_news)}}
    </div>
    <h6 class="mb-3 mt-4">Новая манга</h6>
    <div class="anime-grid">
      {{manga.widget(pagination_new_manga.items, current_user)}}
    </div>
    {% if pagination_new_manga and pagination_new_manga.pages > 1 %}
      {{ pagination.widget(pagination_new_manga, '.index') }}
    {% endif %}
  </div>
  <article class="col-3">
    <h6 class="mb-3">Топ активных пользователей</h6>
    {{top_users.widget(popular_users, moment)}}
    <h6 class="mb-3 mt-4">Часто используемые теги</h6>
    {{tags.widget(popular_tags)}}
    <h6 class="mb-3 mt-4">Новые главы</h6>
    {{chapters.widget(new_chapters)}}
  </article>
</div>
{% endblock %}

app/main/templates/manga_list.html
{% extends "base.html" %}
{% import "_pagination.html" as macros %}
{% import "_manga.html" as manga %}

{% block page_content %}
<form class="d-flex" method="get">
    {{ search_form.search(placeholder="Поиск манги",class_="form-control me-2") }}
    {{ search_form.submit(class_="btn btn-primary") }}
</form>
<h5 class="mb-3 mt-4">Вся манга</h5>
<div class="anime-grid">
    {{manga.widget(pagination.items, current_user)}}
</div>

{% if pagination and pagination.pages > 1 %}
{{ macros.widget(pagination, '.manga_list', search=search_form.search.data ) }}
{% endif %}

{% endblock %}

app/main/templates/news_list.html
{% extends "base.html" %}
{% import "_news.html" as news %}
{% import "_pagination.html" as macros %}

{% block page_content %}
<h5 class="mb-3 mt-4">Все новости</h5>
<div class="news-grid">
    {{news.widget(pagination.items)}}
</div>

{% if pagination and pagination.pages > 1 %}
{{ macros.widget(pagination, '.news_list') }}
{% endif %}

{% endblock %}

app/main/templates/users_list.html
{% extends "base.html" %}
{% import "_pagination.html" as macros %}

{% block page_content %}
<form class="d-flex" method="get">
    {{ search_form.search(placeholder="Поиск пользователей",class_="form-control me-2") }}
    {{ search_form.submit(class_="btn btn-primary") }}
</form>
<h5 class="mb-3 mt-4">Все пользователи</h5>

{% include '_users.html' %}

{% if pagination and pagination.pages > 1 %}
{{ macros.widget(pagination, '.users_list', search=search_form.search.data) }}
{% endif %}

{% endblock %}