app/comment/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, TextAreaField
from wtforms.validators import Length, DataRequired


class CommentForm(FlaskForm):
    comment = TextAreaField('Комментарий',
                            validators=[DataRequired(message='Содержание не должно быть пустым'), Length(1, 1024, message='Длина комментария на манги ограничена 1024 символами.')])
    submit = SubmitField('Отправить')

app/manga/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, MultipleFileField
from wtforms.validators import Length, DataRequired, Regexp
from flask_wtf.file import FileField, FileAllowed, file_required
from .. import manga_upload
from ..models import Manga
from wtforms import ValidationError


class AddMangaForm(FlaskForm):
    image = FileField('', validators=[FileAllowed(manga_upload, message='Только изображения')])
    title = StringField('Название',
                        validators=[DataRequired(message="Поле пусто!"), Length(1, 128, message='От 1 до 128 символов длиной')])
    author = StringField('Автор', validators=[Length(0, 64, message='От 0 до 64 символов длиной')])
    tags = StringField('Теги')
    catalog = TextAreaField('Описание')
    submit = SubmitField()

    def validate_title(self, field):
        if Manga.query.filter_by(title=field.data).first():
            raise ValidationError('Манга существует.')


class EditMangaForm(AddMangaForm):
    def __init__(self, manga, *args, **kwargs):
        super(EditMangaForm, self).__init__(*args, **kwargs)
        self.manga = manga

    def validate_title(self, field):
        if field.data != self.manga.title and \
                Manga.query.filter_by(title=field.data).first():
            raise ValidationError('Манга существует.')


class AddChapterForm(FlaskForm):
    volume = StringField('Том', validators=[Length(1, 32, message='От 1 до 32 символов длиной'), 
                                            Regexp('^[0-9]*$', 0, 'Только цифры!')])
    chapter = StringField('Глава', validators=[Length(1, 32, message='От 1 до 32 символов длиной'),
                                                Regexp('^[0-9]*$', 0, 'Только цифры!')])
    title = StringField('Название',
                        validators=[Length(0, 128, message='До 128 символов длиной')])
    image = MultipleFileField('', id="formFileMultiple", validators=[DataRequired(message='Изображения не загружены!'), 
                                                                    FileAllowed(manga_upload, message='Только изображения!')])
    submit = SubmitField('Добавить')
        

class SearchForm(FlaskForm):
    search = StringField(validators=[DataRequired()])
    submit = SubmitField('Искать')

app/news/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, MultipleFileField
from wtforms.validators import DataRequired, Length
from flask_wtf.file import FileAllowed
from .. import news_upload


class NewsForm(FlaskForm):
    title = StringField('Название',
                        validators=[DataRequired(message="Поле пусто!"), Length(1, 128, message='От 1 до 128 символов длиной')])
    news = TextAreaField('Новость',
                        validators=[DataRequired(message='Содержание не должно быть пустым'), Length(1, 1024, message='Длина новости ограничена 1024 символами.')])
    image = MultipleFileField('', id="formFileMultiple", validators=[FileAllowed(news_upload, message='Только изображения')])
    submit = SubmitField('Опубликовать')

app/comment/__init__.py
from flask import Blueprint

comment = Blueprint('comment', __name__, url_prefix='/comments', template_folder='templates')

from . import views

app/comment/views.py
from .forms import CommentForm
from flask import render_template, redirect, url_for, flash, request
from flask_login import login_required, current_user
from .. import db
from ..models import Manga, News, Comment, Permission
from ..decorators import permission_required
from . import comment


@comment.route('/add_manga_comment/<int:id>', methods=['GET', 'POST'])
@login_required
@permission_required(Permission.COMMENT)
def add_manga_comment(id):
    comment_form = CommentForm()
    manga = Manga.query.get_or_404(id)
    if comment_form.comment.data:
        comment = Comment(
            user=current_user._get_current_object(), 
            manga=manga, 
            body=comment_form.comment.data)
        db.session.add(comment)
        db.session.commit()
    return redirect(url_for('manga.index', id=manga.id))

@comment.route('/add_news_comment/<int:id>', methods=['GET', 'POST'])
@login_required
@permission_required(Permission.COMMENT)
def add_news_comment(id):
    comment_form = CommentForm()
    news = News.query.get_or_404(id)
    if comment_form.comment.data:
        comment = Comment(
            user=current_user._get_current_object(), 
            news=news, 
            body=comment_form.comment.data)
        db.session.add(comment)
        db.session.commit()
    return redirect(url_for('news.index', id=news.id))

@comment.route('/moderate')
@login_required
@permission_required(Permission.MODERATE)
def moderate():
    page = request.args.get('page', 1, type=int)
    pagination = Comment.query.order_by(Comment.timestamp.desc()).paginate(
        page, per_page=15,
        error_out=False)
    return render_template('moderation_comments.html',
                           pagination=pagination, page=page, title="Модерация")


@comment.route('/moderate/enable/<int:id>')
@login_required
@permission_required(Permission.MODERATE)
def moderate_enable(id):
    comment = Comment.query.get_or_404(id)
    comment.disabled = False
    db.session.add(comment)
    db.session.commit()
    return redirect(url_for('.moderate',
                            page=request.args.get('page', 1, type=int)))


@comment.route('/moderate/disable/<int:id>')
@login_required
@permission_required(Permission.MODERATE)
def moderate_disable(id):
    comment = Comment.query.get_or_404(id)
    comment.disabled = True
    db.session.add(comment)
    db.session.commit()
    return redirect(url_for('.moderate',
                            page=request.args.get('page', 1, type=int)))

app/manga/__init__.py
from flask import Blueprint

manga = Blueprint('manga', __name__, url_prefix='/manga', template_folder='templates')

from . import views

app/manga/views.py
from ..comment.forms import CommentForm
from datetime import datetime
from .forms import AddMangaForm, EditMangaForm, AddChapterForm
from . import manga
from flask import render_template, redirect, url_for, flash, request,\
    current_app
from flask_login import login_required, current_user
from .. import db, manga_upload
from ..models import Manga, Permission, Images, Chapter, Comment, Tag
from ..decorators import permission_required

@manga.route('/<int:id>')
def index(id):
    comment_form = CommentForm()
    manga = Manga.query.get_or_404(id)
    page = request.args.get('page', 1, type=int)
    pagination = manga.comments.order_by(Comment.timestamp.desc()).paginate(
        page, per_page=current_app.config['MANGA_COMMENTS_PER_PAGE'],
        error_out=False)
    return render_template("manga.html", comment_form=comment_form, manga=manga, pagination=pagination, title=manga.title)

@manga.route('/add', methods=['GET', 'POST'])
@login_required
@permission_required(Permission.PUBLICATION)
def add():
    add_manga_form = AddMangaForm()
    if add_manga_form.validate_on_submit():
        manga = Manga(
            title=add_manga_form.title.data,
            author=add_manga_form.author.data,
            tags_string=add_manga_form.tags.data,
            catalog=add_manga_form.catalog.data,
            user=current_user._get_current_object()
        )
        if add_manga_form.image.data:
            forder = str(manga.id)
            manga.image = manga_upload.save(add_manga_form.image.data, folder=forder)
        db.session.add(manga)
        db.session.commit()
        flash('Манга %s добавлена.'% manga.title, 'success')
        return redirect(url_for('.index', id=manga.id))
    return render_template("add_manga.html", edit_manga_form=add_manga_form, title="Добавить мангу")


@manga.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
@permission_required(Permission.PUBLICATION)
def edit(id):
    manga = Manga.query.get_or_404(id)
    edit_manga_form = EditMangaForm(manga=manga)
    if edit_manga_form.validate_on_submit():
        manga.title=edit_manga_form.title.data
        manga.author=edit_manga_form.author.data
        manga.tags_string=edit_manga_form.tags.data
        manga.catalog=edit_manga_form.catalog.data
        manga.user=current_user._get_current_object()
        manga.timestamp = datetime.utcnow()
        if edit_manga_form.image.data:
            forder = str(manga.id)
            manga.image = manga_upload.save(edit_manga_form.image.data, folder=forder)
        db.session.add(manga)
        db.session.commit()
        flash('Манга %s обновлена.'% manga.title, 'success')
        return redirect(url_for('.index', id=manga.id))
    edit_manga_form.title.data = manga.title
    edit_manga_form.author.data = manga.author
    edit_manga_form.tags.data = manga.tags_string
    edit_manga_form.catalog.data = manga.catalog
    return render_template("add_manga.html", edit_manga_form=edit_manga_form, manga=manga, title=manga.title)


@manga.route('/read/<int:id>')
@login_required
@permission_required(Permission.FOLLOW)
def follow(id):
    manga = Manga.query.get_or_404(id)
    if current_user.is_reading(manga):
        flash('Вы уже подписаны.', 'warning')
        return redirect(url_for('.index', id=manga.id))
    current_user.read(manga)
    db.session.commit()
    return redirect(url_for('.index', id=manga.id))


@manga.route('/unread/<int:id>')
@login_required
@permission_required(Permission.FOLLOW)
def unfollow(id):
    manga = Manga.query.get_or_404(id)
    if not current_user.is_reading(manga):
        flash('Вы уже подписаны.', 'warning')
        return redirect(url_for('.index', id=manga.id))
    current_user.unread(manga)
    db.session.commit()
    return redirect(url_for('.index', id=manga.id))


@manga.route('/add_chapter/<int:id>', methods=['GET', 'POST'])
@login_required
@permission_required(Permission.PUBLICATION)
def add_chapter(id):
    manga = Manga.query.get_or_404(id)
    add_chapter_form = AddChapterForm()
    if add_chapter_form.validate_on_submit():
        chapter = Chapter(
            volume=add_chapter_form.volume.data,
            chapter=add_chapter_form.chapter.data,
            title=add_chapter_form.title.data,
            user=current_user._get_current_object(),
            manga=manga
        )
        for file in request.files.getlist("image"):
            if file.filename:
                forder = str(manga.id) + "/" + str(add_chapter_form.volume.data) + "/" + str(add_chapter_form.chapter.data)
                image = Images(
                    url = manga_upload.save(file, folder=forder),
                    chapter=chapter
                )
                db.session.add(image)
        db.session.add(chapter)
        db.session.commit()
        flash('Глава опубликована.', 'success')
        return redirect(url_for('.index', id=manga.id))
    return render_template("add_chapter.html", edit_chapter_form=add_chapter_form, manga=manga, title=manga.title)


@manga.route('/delete_chapter/<int:id>/<int:volume>/<int:chapter>', methods=['GET', 'POST'])
@login_required
@permission_required(Permission.PUBLICATION)
def delete_chapter(id, volume, chapter):
    manga = Manga.query.get_or_404(id)

    current_chapter = manga.chapter.filter_by(
        volume=volume,
        chapter=chapter
    ).first_or_404()

    db.session.delete(current_chapter)
    db.session.commit()
    flash('Глава удалена.', 'success')

    return redirect(url_for('.index', id=manga.id))


@manga.route('<int:id>/<int:volume>/<int:chapter>')
def chapter(id, volume, chapter):
    manga = Manga.query.get_or_404(id)
    
    current_chapter = manga.chapter.filter_by(
        volume=volume,
        chapter=chapter
    ).first_or_404()
    
    pagination_images = current_chapter.image.paginate(
        page=request.args.get('page', 0, type=int), 
        per_page=1, 
        error_out=False
    )

    chapters = manga.chapter.all()
    pagination_chapters = manga.chapter.paginate(
        page=chapters.index(current_chapter) + 1,  
        per_page=1,
        error_out=False
    )
    
    title = f"Том {current_chapter.volume} Глава {current_chapter.chapter}"

    return render_template("chapter.html", pagination_chapters=pagination_chapters, current_chapter=current_chapter, chapters=chapters, \
                            pagination_images=pagination_images, manga=manga, title=title)


@manga.route('/tag/<int:id>')
def tag(id):
    tag = Tag.query.get_or_404(id)
    manga =  Manga.query.filter(Manga.tags.any(Tag.id == tag.id)) \
                        .group_by(Manga.id) \
                        .order_by(Manga.timestamp.desc())

    page = request.args.get('page', 1, type=int)
    pagination = manga.paginate(
    page, per_page=current_app.config['MANGA_LIST_PER_PAGE'], 
    error_out=False)
    return render_template('tag.html', pagination=pagination, tag=tag)

app/news/__init__.py
from flask import Blueprint

news = Blueprint('news', __name__, url_prefix='/news', template_folder='../news/templates')

from . import views

app/news/views.py
from flask import render_template
from . import news
from .forms import NewsForm
from ..comment.forms import CommentForm
from flask import render_template, redirect, url_for, flash, request,\
    current_app
from flask_login import login_required, current_user
from .. import db, news_upload
from ..models import News, Images, Comment
from ..decorators import admin_required


@news.route('/<int:id>')
def index(id):
    comment_form = CommentForm()
    news= News.query.get_or_404(id)
    page = request.args.get('page', 1, type=int)
    pagination = news.comments.order_by(Comment.timestamp.desc()).paginate(
        page, per_page=current_app.config['MANGA_COMMENTS_PER_PAGE'],
        error_out=False)
    return render_template('news.html', comment_form=comment_form, news=news, pagination=pagination, title=news.title)


@news.route('/add', methods=['GET', 'POST'])
@login_required
@admin_required
def add():
    news_form = NewsForm()
    if news_form.validate_on_submit():
        news = News(
            title=news_form.title.data,
            body=news_form.news.data,
            user=current_user._get_current_object()
        )
        for file in request.files.getlist("image"):
            if file.filename:
                forder = str(news.id)
                image = Images(
                    url = news_upload.save(file, folder=forder),
                    news=news
                )
                db.session.add(image)
        db.session.add(news)
        db.session.commit()
        flash('Новость опубликована.', 'success')
        return redirect(url_for('.index', id=news.id))
    return render_template('add_news.html', news_form=news_form, title=u"Создать новость")

app/user/__init__.py
from flask import Blueprint

user = Blueprint('user', __name__, url_prefix='/user', template_folder='templates')

from . import views

app/templates/_chapters.html
{% macro widget(new_chapter) %}
    {% for c in new_chapter %}
        <div class="mb-3 d-flex" >
            <div>
                <div class="poster sm-poster" data-bs-toggle="tooltip" data-bs-html="true" data-bs-placement="right"
                title="<b>{{ c.Manga.title }}</b> <p>{{c.Manga.catalog}}</p>" style="background-image: url({{ c.Manga.image_url() }})">
                </div>
            </div>
            <div class="ms-2">
                <h6 class="card-title"><a class="link-dark" href="{{ url_for('manga.index', id=c.Manga.id) }}">{{ c.Manga.title }}</a></h6>
                <p class="mb-0">Том {{c.Chapter.volume}} Глава {{c.Chapter.chapter}}</p>
            </div>
        </div>
    {% endfor %}
{% endmacro %}

app/templates/_comments.html
{% for item in pagination.items %}
<div class="container px-0 py-2 my-2 d-flex align-items-start">
    <div class="avatar avatar-small ms-2" style="background-image: url({{ item.user.avatar_url() }}) ">
    </div>
    <div class="ms-2 d-flex flex-column flex-fill">
        <div class="fw-bold d-flex justify-content-between align-items-center pe-2"> 
            <div class="fw-bold"><a class="link-dark" href="{{ url_for('user.index', id = item.user.id) }}">{{ item.user.username }}</a>
            {% if item.user.is_administrator %} 
                <small class="text-muted"> •</small> <small class="text-primary"> {{ item.user.role.name }}</small>
            {% endif %}
            </div>
            <small class="text-muted">{{ moment(item.timestamp).format('L') }}</small>
        </div>
        <!-- <p class="card-title">Комментарий к <a class="link-primary" href="">Не издевайся, Нагаторо-сан </a></p> -->
        <p>
            {% if item.disabled or item.user.banned %}
                <i>Данный комментарий был заблокирован модератором.</i>
            {% endif %}
        </p>
        <p>
            {% if moderate or not item.disabled and not item.user.banned %}
                {{ item.body }}
            {% endif %}
        </p>
        <div class="d-flex justify-content-end">
            {% if moderate %}
                {% if item.disabled %}
                    <a type="button" href="{{ url_for('.moderate_enable', id=item.id, page=page) }}" class="btn btn-light ms-2">Разблокировать</a>
                {% else %}
                    <a type="button" href="{{ url_for('.moderate_disable', id=item.id, page=page) }}" class="btn btn-edit-admin ms-2">Заблокировать</a>
                {% endif %}
            {% endif %}
        </div>
    </div>
</div>
{% endfor %}

app/templates/_error_form_message.html
{% macro error(field) %}
  {% if field.errors %}
    <ul class="m-0 px-0">
    {% for error in field.errors %}
      <small class="text-danger">{{ error }}</small>
    {% endfor %}
    </ul>
  {% endif %}
{% endmacro %}

app/templates/_manga.html
{% macro widget(manga, current_user) %}
  {% for item in manga %}
    <div class="mb-2">
      <div class="d-flex flex-column justify-content-center" >
        <div class="p-0 position-relative poster md-poster" data-bs-toggle="tooltip" data-bs-html="true" data-bs-placement="right"
            title="<b>{{ item.title }}</b> <p>{{item.catalog}}</p>" style="background-image: url({{ item.image_url() }})">
          {% if current_user.is_reading(item) %}
            <button type="button" class="btn ms-2 mt-2" style="background-color: #00e676; color: #Fff; pointer-events: none">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bookmark-fill" viewBox="0 0 16 16">
                <path d="M2 2v13.5a.5.5 0 0 0 .74.439L8 13.069l5.26 2.87A.5.5 0 0 0 14 15.5V2a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2z"/>
              </svg>
            </button>
          {% endif %}
        </div>
        <h6 class="card-title mt-2"><a class="link-dark" href="{{ url_for('manga.index', id = item.id) }}">{{ item.title }}</a></h6>
      </div>
    </div>
  {% endfor %}
{% endmacro %}

app/templates/_news.html
{% macro widget(news) %}
    {% for item in news %}
        <div class="mb-2">
            <div class="d-flex flex-column justify-content-center mb-3" >
                <div class="poster news-poster p-0" style="background-image: url({{ item.get_poster() }})">
                </div>
                <h6 class="card-title mt-1"><a class="link-dark" href="{{ url_for('news.index', id=item.id) }}">{{ item.title }}</a></h6>
            </div>
        </div>
    {% endfor %}
{% endmacro %}

app/templates/_pagination.html
{% macro widget(pagination, endpoint, fragment='') %}
<ul class="pagination mt-4 mb-5">
    <li class="page-item {% if not pagination.has_prev %} disabled {% endif %} ">
        <a class="page-link" href="{% if pagination.has_prev %}{{ url_for(endpoint, page=pagination.prev_num, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
            ←
        </a>
    </li>
    {% for p in pagination.iter_pages() %}
        {% if p %}
            {% if p == pagination.page %}
            <li class="page-item active">
                <a class="page-link" href="{{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="{{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
            </li>
            {% endif %}
        {% else %}
        <li class="page-item disabled"><a class="page-link" href="#">&hellip;</a></li>
        {% endif %}
    {% endfor %}
    <li class="page-item {% if not pagination.has_next %} disabled {% endif %}">
        <a class="page-link" href="{% if pagination.has_next %}{{ url_for(endpoint, page=pagination.next_num, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
            →
        </a>
    </li>
</ul>
{% endmacro %}

app/templates/_tags.html
{% macro widget(tags) %}
    {% for tag in tags %}
        <a type="button" href="{{ url_for('manga.tag', id = tag.id) }}" class="btn btn-light mb-2">{{ tag.name }}</a>
    {% endfor %}
{% endmacro %}

app/templates/_top_users.html
{% macro widget(popular_users, moment) %}
    {% for user in popular_users %}
        <div class="mb-3 d-flex" >
            <div>
                <div class="avatar avatar-top-users me-2" style="background-image: url({{ user.avatar_url() }})">
                </div>
            </div>
            <div class="d-flex row align-items-center">
                <h6 class="card-title">
                <a class="link-dark" href="{{ url_for('user.index', id = user.id) }}">{{ user.username }}</a>
                </h6>
                <small class="m-0">онлайн {{ moment(user.last_seen).fromNow() }}</small>
            </div>
        </div>
    {% endfor %}
{% endmacro %}

app/templates/_users.html
{% for item in pagination.items %}
    {% if item and item != user %}
    <div class="d-flex justify-content-between align-items-center p-2">
        <div class="avatar avatar-small" style="background-image: url({{ item.avatar_url() }})">
        </div>
        <div class="ms-3 me-auto">
            <div class="fw-bold"><a class="link-dark" href="{{ url_for('user.index', id = item.id) }}">{{ item.username }}</a>                 
                {% if item.is_administrator %} 
                    <small class="text-muted"> •</small> <small class="text-primary"> {{ item.role.name }}</small>
                {% endif %}
            </div>
            <small class="text-muted">{{ moment(item.last_seen).fromNow() }}</small>
        </div>
    </div>
    {% endif %}
{% endfor %}

app/templates/base.html
{% extends "bootstrap/base.html" %}
{% from 'bootstrap/utils.html' import flashed_messages %}

{% block title %}
    {% if title %}
        {{ title }} - Manga Library
    {% else %}
        Manga Library
    {% endif %}
{% endblock %}

{% block styles %}
    <link rel="icon" href="{{ url_for('static', filename='img/favicon.ico') }}" type="image/x-icon">
    <link href="{{ url_for('static',filename='css/bootstrap/css/bootstrap.css') }}" rel="stylesheet">
    <link href="{{ url_for('static',filename='css/main.css') }}" rel="stylesheet">
{% endblock %}
{% block navbar %}
<nav class="navbar navbar-expand-md navbar-dark bg-primary">
    <div class="container-md">
        <a class="navbar-brand" href="{{ url_for('main.index') }}">
            <img id="logo" src="{{ url_for('static',filename='img/logo.svg') }}" class="d-inline-block align-text-top" alt="" width="27.88" height="30">
            MangaLibrary
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="btn btn-primary" href="{{ url_for('main.manga_list') }}">Манга</a>
                <a class="btn btn-primary" href="{{ url_for('main.news_list') }}">Новости</a>
                <a class="btn btn-primary" href="{{ url_for('main.users_list') }}">Пользователи</a>
            </div>
            <div class="navbar-nav ms-auto">
                {% if current_user.is_authenticated %}
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown d-flex align-items-center">
                        <a class="nav-link dropdown-toggle d-flex align-items-center" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <div class="avatar avatar-header me-2" style="background-image: url({{ current_user.avatar_url() }}) ">
                            </div>
                            {{ current_user.username }}
                        </a>
                        <ul class="dropdown-menu dropdown-menu-light" aria-labelledby="navbarDarkDropdownMenuLink">
                            <li><a class="dropdown-item" href="{{ url_for('user.index', id=current_user.id) }}">Мой профиль</a></li>
                            {% if current_user.can(Permission.MODERATE) %}
                                <li><a class="dropdown-item" href="{{ url_for('comment.moderate') }}">Модерация</a></li>
                            {% endif %}
                            {% if current_user.is_administrator %}
                                <li><a class="dropdown-item" href="{{ url_for('news.add') }}">Добавить новость</a></li>
                            {% endif %}
                            {% if current_user.can(Permission.PUBLICATION) %}
                            <li><a class="dropdown-item" href="{{ url_for('manga.add') }}">Добавить мангу</a></li>
                            {% endif %}
                            <li><a class="dropdown-item" href="{{ url_for('auth.change_email_request') }}">Изменить почту</a></li>
                            <li><a class="dropdown-item" href="{{ url_for('auth.change_password') }}">Измениить пароль</a></li>
                            <li><a class="dropdown-item" href="{{ url_for('auth.logout') }}">Выйти</a></li>
                        </ul>
                        </li>
                    </ul>
                    {% else %}
                        <a class="btn btn-primary mx-2" href="{{ url_for('auth.login') }}">Вход</a>
                        <a class="btn btn-outline-light" href="{{ url_for('auth.register') }}">Регистрация</a>
                    {% endif %}
            </div>
        </div>
    </div>
</nav>
{% endblock %}

{% block content %}

<main class="container my-4 min-vh-100">
    <div class="container px-0">
        {% set message = get_flashed_messages(with_categories=True)%}
        {% for type, message in message %}
        <div class="alert alert-{{ type }} d-flex align-items-center justify-content-between">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
    </div>
    {% block page_content %}{% endblock %}
</main>

<footer class="footer py-3 bg-primary align-bottom">
    <div class="container-fluid d-inline-flex justify-content-center mb-2">
        <a class="navbar-brand text-white" href="{{ url_for('main.index') }}">
            <img id="logo" src="{{ url_for('static',filename='img/logo.svg') }}" class="d-inline-block align-text-top" alt="" width="27.88" height="30">
            MangaLibrary
        </a>
    </div>
    <div class="container-fluid text-muted d-inline-flex justify-content-center">
        <a class="btn text-white"><small class="fw-bold">Правообладателям</small></a>
        <a class="btn text-white"><small>Вконтакте</small></a>
        <a class="btn text-white"><small class="fw-bold">О проекте</small></a>
        <a class="btn text-white"><small>Discord</small></a>
    </div>
</footer>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{{ moment.lang('ru') }}
<script src="{{ url_for('static',filename='js/bootstrap/js/bootstrap.js') }}"></script>
<script src="{{ url_for('static',filename='js/bootstrap/js/bootstrap.bundle.js') }}"></script>
<script src="{{ url_for('static',filename='js/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<script>
    var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
    var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
      return new bootstrap.Tooltip(tooltipTriggerEl)
    })
</script>
{% endblock %}